### ISSUE TITLE
won't start correctly

### ISSUE THREAD

**Issue by aleprovencio** [kbarrette/mediummode#3]
Hello,
I always have to :MediumModeDisable (or Toggle) and than :MediumModeEnable for it to start and it's worth mention that when called for the first time both Disable and Toggle commands throw errors like: error detected while processing function <SNR>77_MediumModeToggle.

vim 7.3-865

**Comment by kbarrette** [comment]
I'd love to be able to reproduce this - is there anything informative in the output of `:mess`?  Would you mind sharing your `.vimrc`?

**Comment by aleprovencio** [comment]
I will not reproduce the :messages as they show because they look like a ":mess" in my portuguese install :) However it would not change too much of what I've described earlier. I've made a sandbox with minimal pathogen install and git clonned mediummode. The rc is exactly as this:

execute pathogen#infect()
syntax on
filetype plugin indent on

It's possible that I've made wrong assumptions of this issue since I'm in a rush for a 12day trip, and also because of this I may not be able to help you like I would like to, but if this is still opened after that, I'm willing to be useful where I can.

**Comment by muonoum** [comment]
I have the same problem. Here is the output from :mess after issuing :MediumModeDisable:

```
Error detected while processing function <SNR>5_MediumModeDisable:
line    3:
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
line    3:  
E31: No such mapping
line    4:  
E31: No such mapping
```

Issuing :MediumModeEnable at this point enables the plugin correctly.

.vimrc used for testing:

```
set nocompatible
filetype off
set rtp+=$HOME/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'kbarrette/mediummode'

filetype plugin indent on
```

```
:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Mar 25 2013 19:55:22)
Included patches: 1-875
```

**Comment by kbarrette** [comment]
Great - I'll attempt to reproduce and repair this as soon as I have time.

**Comment by mbadran** [comment]
Same issue occurs for me.

**Comment by kbarrette** [comment]
Thanks for the error reports - I've just pushed a change that should fix this.  If someone could please confirm that everything is now working as expected, I'd appreciate it.

**Comment by aleprovencio** [comment]
Seems to be fine, thank you

**Comment by kbarrette** [comment]
Thanks for letting me know, @aleprovencio !
